# SPDX-License-Identifier: LGPL-2.1-or-later
# origin: https://github.com/systemd/particleos.git

[Partition]
Type=usr
Label=%M-%A
Format=erofs
CopyFiles=/usr:/
Verity=data
VerityMatchKey=usr
Minimize=yes
Compression=zstd
SplitName=usr
