[Content]
Packages=
   phosh-full
   phosh-phone
   phrog
   plymouth-theme-phosh
WithRecommends=true
RemovePackages=
   gnome-software-plugin-deb
   gnome-user-docs
   packagekit
   x11-xserver-utils
KernelCommandLine=
   quiet
   splash
   console=ttyS0
