[Content]
Packages=
   alsa-ucm-conf
   alsa-utils
   bluetooth
   callaudiod
   libspa-0.2-bluetooth
   phosh-full
   phosh-phone
   phosh-tablet
   phrog
   plymouth-theme-phosh
   pipewire-audio
   wireplumber

RemovePackages=
   gnome-software-plugin-deb
   gnome-user-docs
   packagekit
   x11-xserver-utils
