---

stages:
  - build
  - test

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    # Don't trigger a branch pipeline if there is an open MR
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH

variables:
  PHOSH_IMAGE_BRANCH: main
  PHOSH_IMAGE_UPLOAD_OPTS: --verbose

default:
  timeout: 6 hours
  # Allow jobs to be caneled on new commits
  interruptible: true
  # Retry on infra hickups automatically
  retry:
    max: 1
    when:
      - 'api_failure'
      - 'runner_system_failure'
      - 'scheduler_failure'
      - 'stuck_or_timeout_failure'

build:mkosi:nightly:amd64:
  stage: build
  tags: ["phosh-images"]
  variables:
    ARCH: amd64
  script:
    - XDG_CACHE_HOME=~/.cache make clean bengalos-${ARCH}
    - |
      if [ -n "${PHOSH_IMAGE_HOST}" ] && \
         [ -n "${PHOSH_IMAGE_UPLOAD}" ] && \
         [ "${CI_COMMIT_BRANCH}" = "${PHOSH_IMAGE_BRANCH}" ]; then
        ls -lh build/BengalOS-*
        xz -zk build/BengalOS-${ARCH}_*.raw
        time rsync ${PHOSH_IMAGE_UPLOAD_OPTS} \
                             BengalOS-${ARCH}_*.raw.xz \
                             "${PHOSH_IMAGE_HOST}:"
      else
        echo "Skipping upload on ${CI_COMMIT_BRANCH}."
      fi

lint:
  stage: test
  needs: []
  image: 'godiug/website:v0.0.2025-09-14'
  script:
    - make lint
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        paths:
          - "*.md"
