---

stages:
  - build

variables:
  PHOSH_IMAGE_BRANCH: main
  PHOSH_IMAGE_UPLOAD_OPTS: --verbose

default:
  timeout: 6 hours
  # Allow jobs to be caneled on new commits
  interruptible: true
  # Retry on infra hickups automatically
  retry:
    max: 1
    when:
      - 'api_failure'
      - 'runner_system_failure'
      - 'scheduler_failure'
      - 'stuck_or_timeout_failure'

build:debos:nightly:amd64:
  stage: build
  tags: ["phosh-images"]
  variables:
    DEBOS_CMD: "debos"
    ARCH: amd64
  script:
    - "make ${ARCH}"
    - |
      if [ -n "${PHOSH_IMAGE_HOST}" ] && \
         [ -n "${PHOSH_IMAGE_UPLOAD}" ] && \
         [ "${CI_COMMIT_BRANCH}" = "${PHOSH_IMAGE_BRANCH}" ]; then
        time rsync ${PHOSH_IMAGE_UPLOAD_OPTS} \
                             phosh-os-${ARCH}-phosh-*.img.xz \
                             phosh-os-${ARCH}-phosh-*.img.bmap \
                             "${PHOSH_IMAGE_HOST}:"
      else
        echo "Skipping upload on ${CI_COMMIT_BRANCH}."
      fi

build:mkosi:nightly:amd64:
  allow_failure: true
  stage: build
  tags: ["phosh-images"]
  script:
    - python3 configure.py build --password 1234
    - mkosi -C build -i
    - tar -czvf phosh-os-mkosi-amd64.img.gz build/image.raw
    - |
      if [ -n "${PHOSH_IMAGE_HOST}" ] && \
         [ -n "${PHOSH_IMAGE_UPLOAD}" ] && \
         [ "${CI_COMMIT_BRANCH}" = "${PHOSH_IMAGE_BRANCH}" ]; then
        time rsync ${PHOSH_IMAGE_UPLOAD_OPTS} \
                             phosh-os-mkosi-amd64.img.gz \
                             "${PHOSH_IMAGE_HOST}:"
      else
        echo "Skipping upload on ${CI_COMMIT_BRANCH}."
      fi
