[Distribution]
Distribution=debian
Release=forky

[Output]
ImageId=BengalOS
Format=disk

[Content]
UnifiedKernelImageFormat=%i_%v_%a
Bootable=true
WithRecommends=true
Packages=
   busybox
   ca-certificates
   dosfstools
   e2fsprogs
   file
   hwdata
   inetutils-ping
   iptables
   iw
   kbd
   locales
   login
   mmc-utils
   network-manager
   openssl
   passwd
   rfkill
   rtkit
   sudo
   systemd
   systemd-boot
   systemd-resolved
   usb-modeswitch
   usbutils
   wireless-regdb
   wireless-tools
   wpasupplicant

RootPassword=root

KernelCommandLine=
   quiet
   splash
