[Distribution]
Architecture=arm64
Repositories=contrib
             non-free
             non-free-firmware

[Content]
Packages=
   qcom-support-common
   linux-image-6.18-sdm845

[Output]
ImageId=BengalOS-sdm845
